def build(bld):
    obj = bld.create_ns3_program('fuzzylite', ['fuzzylite'])
    obj.source = 'fuzzylite.cc'
    obj.includes = [obj.includes, '/home/fuzzylite/fuzzylite']
    obj.libpath = '/home/fuzzylite/release/bin'
    obj.lib = 'fuzzylite'
